language: python
python:
  - 3.9-dev
  - 3.8
  - 3.7
  - 3.6
sudo: false
dist: xenial
services:
  - xvfb
env:
  matrix:
    - GROUP=python
matrix:
  include:
    - python: 3.8
      env: GROUP=js
cache:
  pip: true
  directories:
    - nbdime/webapp/node_modules # NPM packages
    - nbdime-web/node_modules # NPM packages
    - $HOME/.npm
before_install:
  - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"
  - pip install -U pip setuptools
  - nvm install 8
  - |
    if [[ $GROUP == python ]]; then
      pip install codecov
    elif [[ $GROUP == js ]]; then
      npm install -g codecov
    fi
install:
  # Don't use -v with JS as travis chokes with [Errno 11] write could not complete without blocking
  - |
    if [[ $GROUP == python ]]; then
      pip install --upgrade --upgrade-strategy=eager ".[test]" -v
    elif [[ $GROUP == js ]]; then
      pip install --upgrade --upgrade-strategy=eager -e ".[test]"
    fi
before_script:
  # Set up a virtual screen for Firefox browser testing:
  - |
    if [[ $GROUP == js ]]; then
      export CHROME_BIN=chromium-browser
    fi
    git config --global user.email travis@fake.com
    git config --global user.name "Travis CI"
script:
  - |
    if [[ $GROUP == python ]]; then
      EXIT_STATUS=0
      pushd $(mktemp -d)
      py.test -l --cov-report xml:$TRAVIS_BUILD_DIR/coverage.xml --cov=nbdime --pyargs nbdime || EXIT_STATUS=$?
      popd
      exit $EXIT_STATUS
    elif [[ $GROUP == js ]]; then
      npm test
    fi
before_cache:
  # Do not cache our own package
  - |
    rm -rf nbdime/webapp/node_modules/nbdime
after_success:
    - codecov
