# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# environment variables
environment:
  nodejs_version: "8.15"
  matrix:
    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.x"
      PYTHON_MAJOR: 3
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_MAJOR: 2
      PYTHON_ARCH: "32"

# build cache to preserve files/folders between builds
cache:
  - '%AppData%/npm-cache'

# scripts that run after cloning repository
install:
  # Install node:
  - ps: Install-Product node $env:nodejs_version
  # Ensure python scripts are from right version:
  - 'SET "PATH=%PYTHON%\Scripts;%PYTHON%;%PATH%"'
  # Install coverage utilities:
  - 'pip install codecov'
  # Package up sdist for our package:
  - 'python setup.py sdist'
  - 'for /f %%i in (''dir .\dist\nbdime-*.tar.gz /B'') do set fname=%%i'
  # Install our package:
  - 'pip install --upgrade --upgrade-strategy=eager ".\dist\%fname%[test]"'

build: off

# scripts to run before tests
before_test:
  - git config --global user.email appveyor@fake.com
  - git config --global user.name "AppVeyor CI"
  # Mercurial config:
  - ps: '$hgconfig = "[ui]`r`nusername = AppVeyor CI <appveyor@fake.com>"'
  - ps: '$hgconfig | Set-Content ($HOME + "\mercurial.ini")'
  - set "tmptestdir=%tmp%\nbdime-%RANDOM%"
  - mkdir "%tmptestdir%"
  - cd "%tmptestdir%"


# to run your custom scripts instead of automatic tests
test_script:
  - 'py.test -l --cov-report xml:"%APPVEYOR_BUILD_FOLDER%\coverage.xml" --cov=nbdime --pyargs nbdime'

on_success:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - codecov -X gcov --file "%APPVEYOR_BUILD_FOLDER%\coverage.xml"
